### ISSUE TITLE
Issue with concatenation when using data.frame format

### ISSUE THREAD

**Issue by pollytatouin** [christophsax/tsbox#166] opened 2019-07-24 20:55 UTC
Hi,

I'm having the following issue: when I start from a ts-boxable data.frame and compute the period-to-period growth rate, I can't concatenate the result with the original data.frame due to 

`Error in rbindlist(ll.dts) : 
  Class attributes at column 1 of input list at position 2 does not match with column 1 of input list at position 1. Coercion of objects of class 'factor' alone is handled internally by rbind/rbindlist at the moment.` 

or sometimes

`Error: if present, id columns must be the same for all objects`

This does not happen if my series are in `ts` format. It seems to be due to the growth rate function dropping the `id` column. 

Reproducible examples:

```
require(tsbox)
require(dplyr)

# Works
df <- data.frame(time = seq.Date(from = as.Date("2010-01-01"), by = "q", length.out = 10), id = "A", value = runif(10), stringsAsFactors = F) %>% 
  ts_ts()
pp <- ts_pc(df)
ts_c(df, pp)

# Does not work
df <- data.frame(time = seq.Date(from = as.Date("2010-01-01"), by = "q", length.out = 10), id = "A", value = runif(10), stringsAsFactors = F) %>% 
  ts_df()
ts_boxable(df)
pp <- ts_pc(df)
ts_c(df, pp)

df <- data.frame(time = seq.Date(from = as.Date("2010-01-01"), by = "q", length.out = 10), id = "A", value = runif(10), stringsAsFactors = T) %>% 
  ts_df()
ts_boxable(df)
pp <- ts_pc(df)
ts_c(df, pp)
```

I remember that I did not have this issue in the past, so it must be linked to one of the recent-ish updates. Any help would be greatly appreciated.

**Comment by christophsax** [comment] 2019-07-25 09:31
Thanks, I can confirm. `ts_c` is generally cleverer than in the early versions, but this is not intendet. Will fix. 
``` r
library(tsbox)

# single series, with and wo id col
with_id <- wo_id <- ts_df(mdeaths)
with_id$id <- "mdeaths"

ts_c(wo_id, with_id)                           # does not work
#> Column 3 ['id'] of item 2 appears in position 1 in item 1. Set use.names=TRUE to match by column name, or use.names=FALSE to ignore column names. use.names='check' (default from v1.12.2) emits this message and proceeds as if use.names=FALSE for  backwards compatibility. See news item 5 in v1.12.2 for options to control this message.
#> Error in rbindlist(ll.dts): Class attribute on column 1 of item 2 does not match with column 1 of item 1.
head(ts_c(with_id, with_id))                   # does work
#>         time value      id
#> 1 1974-01-01  2134 mdeaths
#> 2 1974-02-01  1863 mdeaths
#> 3 1974-03-01  1877 mdeaths
#> 4 1974-04-01  1877 mdeaths
#> 5 1974-05-01  1492 mdeaths
#> 6 1974-06-01  1249 mdeaths

# if a single series wo id is combinded to multiple series, things are fine
head(ts_c(wo_id, ts_c(mdeaths, fdeaths)))      # does work
#>      id       time value
#> 1 wo_id 1974-01-01  2134
#> 2 wo_id 1974-02-01  1863
#> 3 wo_id 1974-03-01  1877
#> 4 wo_id 1974-04-01  1877
#> 5 wo_id 1974-05-01  1492
#> 6 wo_id 1974-06-01  1249
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by christophsax** [comment] 2019-07-25 09:55
There are actually two problems here. The first is that mismatching id positions caused a problem in `ts_c`. This is fixed in my latest commit:

``` r
library(tsbox)
with_id <- wo_id <- ts_df(mdeaths)
with_id$id <- "mdeaths"
head(ts_c(wo_id, with_id))
#>      id       time value
#> 1 wo_id 1974-01-01  2134
#> 2 wo_id 1974-02-01  1863
#> 3 wo_id 1974-03-01  1877
#> 4 wo_id 1974-04-01  1877
#> 5 wo_id 1974-05-01  1492
#> 6 wo_id 1974-06-01  1249
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


The second is that that `ts_pc`, *unlike* other ts-functions, drops the id column. I guess it should not.

``` r
library(tsbox)
with_id <- wo_id <- ts_df(mdeaths)
with_id$id <- "mdeaths"

head(ts_pc(with_id))
#>         time       value
#> 1 1974-01-01          NA
#> 2 1974-02-01 -12.6991565
#> 3 1974-03-01   0.7514761
#> 4 1974-04-01   0.0000000
#> 5 1974-05-01 -20.5114544
#> 6 1974-06-01 -16.2868633
head(ts_pc(wo_id))
#>         time       value
#> 1 1974-01-01          NA
#> 2 1974-02-01 -12.6991565
#> 3 1974-03-01   0.7514761
#> 4 1974-04-01   0.0000000
#> 5 1974-05-01 -20.5114544
#> 6 1974-06-01 -16.2868633

head(ts_span(with_id))
#>         time value      id
#> 1 1974-01-01  2134 mdeaths
#> 2 1974-02-01  1863 mdeaths
#> 3 1974-03-01  1877 mdeaths
#> 4 1974-04-01  1877 mdeaths
#> 5 1974-05-01  1492 mdeaths
#> 6 1974-06-01  1249 mdeaths
head(ts_span(wo_id))
#>         time value
#> 1 1974-01-01  2134
#> 2 1974-02-01  1863
#> 3 1974-03-01  1877
#> 4 1974-04-01  1877
#> 5 1974-05-01  1492
#> 6 1974-06-01  1249
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pollytatouin** [comment] 2019-07-25 11:42
Yes, I think you put the finger right on it! I was indeed under the impression that previous versions of ts_pc() and the like used not to drop the 'id' column, but I might be mistaken.

I'll give it a try today.

Thank you

**Comment by christophsax** [comment] 2019-07-25 11:44
Both issues should be fixed in the latest dev version.

``` r
library(tsbox)
with_id <- wo_id <- ts_df(mdeaths)
with_id$id <- "mdeaths"

head(ts_pc(with_id))
#>         time       value      id
#> 1 1974-01-01          NA mdeaths
#> 2 1974-02-01 -12.6991565 mdeaths
#> 3 1974-03-01   0.7514761 mdeaths
#> 4 1974-04-01   0.0000000 mdeaths
#> 5 1974-05-01 -20.5114544 mdeaths
#> 6 1974-06-01 -16.2868633 mdeaths
head(ts_pc(wo_id))
#>         time       value
#> 1 1974-01-01          NA
#> 2 1974-02-01 -12.6991565
#> 3 1974-03-01   0.7514761
#> 4 1974-04-01   0.0000000
#> 5 1974-05-01 -20.5114544
#> 6 1974-06-01 -16.2868633
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pollytatouin** [comment] 2019-07-25 17:01
These issues seem solved, thank you.

However, would it be complicated to have ts_pc() and the like to return a standard column ordering of time-id-value ? I know the ts_* functions are able to deal with this regardless of the ordering, but it's convenient to use with other functions to know that the last column will always contain the values.

Perhaps that's too refined though, I let you judge.

**Comment by christophsax** [comment] 2019-07-25 17:09
I think the returned object should have the same column order as in the input. I just committed to master, and now it does:

``` r
library(tsbox)
# single series, with and wo id col
with_id <- wo_id <- ts_df(mdeaths)
with_id$id <- "mdeaths"

head(ts_pc(with_id))
#>         time       value      id
#> 1 1974-01-01          NA mdeaths
#> 2 1974-02-01 -12.6991565 mdeaths
#> 3 1974-03-01   0.7514761 mdeaths
#> 4 1974-04-01   0.0000000 mdeaths
#> 5 1974-05-01 -20.5114544 mdeaths
#> 6 1974-06-01 -16.2868633 mdeaths
head(ts_pc(with_id[, c(2, 1, 3)]))
#>         value       time      id
#> 1          NA 1974-01-01 mdeaths
#> 2 -12.6991565 1974-02-01 mdeaths
#> 3   0.7514761 1974-03-01 mdeaths
#> 4   0.0000000 1974-04-01 mdeaths
#> 5 -20.5114544 1974-05-01 mdeaths
#> 6 -16.2868633 1974-06-01 mdeaths

# or, more standard
head(ts_pc(with_id[, c(3, 1, 2)]))
#>        id       time       value
#> 1 mdeaths 1974-01-01          NA
#> 2 mdeaths 1974-02-01 -12.6991565
#> 3 mdeaths 1974-03-01   0.7514761
#> 4 mdeaths 1974-04-01   0.0000000
#> 5 mdeaths 1974-05-01 -20.5114544
#> 6 mdeaths 1974-06-01 -16.2868633
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Does that make sense?

**Comment by pollytatouin** [comment] 2019-07-25 19:00
I personally prefer having the functions re-arranging the order for me. For instance I often use them to standardize my series: once they've passed through as ts_* function, I know what the output will look like.

There's certainly a case to be made for the opposite though, I'd have to think about it more...

**Comment by christophsax** [comment] 2019-07-26 09:12
With respect to re-arranging: Do you know `ts_default`? It aims to rename the colnames but it could also do default re-arranging, perhaps with an option to turn it off. 

That would be consistent: Usually, ts-boxable functions do not change colnames and order, and `ts_default` allows you to standardize both.

Could that be useful?

**Comment by pollytatouin** [comment] 2019-07-26 16:32
You're right, `ts_default` already addressed part of these issues. I've been working with series formatted differently than usual lately, so my confusion might just be coming from that. I will keep you posted if I run into other hurdles that seem avoidable.

That said, I think having `ts_default` re-arrange the columns ordering could indeed be interesting, thus almost fully putting the series in a default format. "almost" because it does not rename an id column to "id", which could be worth considering?

``` r
require(tsbox)
#> Loading required package: tsbox
df <- ts_df(ts_c(mdeaths, fdeaths))
colnames(df) <- c("series", "date", "count")
head(ts_default(df))
#> [time]: 'date' [value]: 'count'
#>    series       time value
#> 1 mdeaths 1974-01-01  2134
#> 2 mdeaths 1974-02-01  1863
#> 3 mdeaths 1974-03-01  1877
#> 4 mdeaths 1974-04-01  1877
#> 5 mdeaths 1974-05-01  1492
#> 6 mdeaths 1974-06-01  1249
```

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by christophsax** [comment] 2019-07-27 16:47
`ts_default` now restores the the default order as well, I think that is useful:

``` r
require(tsbox)
#> Loading required package: tsbox
df <- ts_df(ts_c(mdeaths, fdeaths))
colnames(df) <- c("series", "date", "count")
df_reordered <- df[, c(3, 2, 1)]
head(ts_default(df_reordered))
#> [time]: 'date' [value]: 'count'
#>    series       time value
#> 1 mdeaths 1974-01-01  2134
#> 2 mdeaths 1974-02-01  1863
#> 3 mdeaths 1974-03-01  1877
#> 4 mdeaths 1974-04-01  1877
#> 5 mdeaths 1974-05-01  1492
#> 6 mdeaths 1974-06-01  1249
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The reason why `series` is not renamed to `id` is that tsbox does not care about the naming of the id column(s). There may be zero or several id columns, e.g.:

``` r
library(tsbox)
ts_default(tsibbledata::global_economy)
#> Loading required namespace: tsibble
#> Ignoring non-numeric measure vars (Code).
#> [time]: 'Year'
#> # A tsibble: 90,900 x 4 [1D] <Europe/Berlin>
#> # Key:       Country, id [1,578]
#>    Country     id    time             value
#>    <fct>       <fct> <date>           <dbl>
#>  1 Afghanistan GDP   1960-01-01  537777811.
#>  2 Afghanistan GDP   1961-01-01  548888896.
#>  3 Afghanistan GDP   1962-01-01  546666678.
#>  4 Afghanistan GDP   1963-01-01  751111191.
#>  5 Afghanistan GDP   1964-01-01  800000044.
#>  6 Afghanistan GDP   1965-01-01 1006666638.
#>  7 Afghanistan GDP   1966-01-01 1399999967.
#>  8 Afghanistan GDP   1967-01-01 1673333418.
#>  9 Afghanistan GDP   1968-01-01 1373333367.
#> 10 Afghanistan GDP   1969-01-01 1408888922.
#> # … with 90,890 more rows
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So a 'default' name for id coulum(s) does not make too much sense i.m.O.

**Comment by pollytatouin** [comment] 2019-07-31 18:03
Hi Chris,

Thanks for these updates. I agree, the "id" renaming is likely not a good idea.

I'm still facing some issues with scripts that I wrote a few months ago that used tsbox. For instance, I used to be able to concatenate ts_boxable data.frames that did not have an "id" column, but for which the column containing the values was named according to the series.

``` r
require(tsbox)
#> Loading required package: tsbox


ts1 <- ts_df(mdeaths)
ts2 <- ts_df(fdeaths)

colnames(ts1) <- c("time","mdeaths")
colnames(ts2) <- c("time", "fdeaths")

ts_c(ts1, ts2)
#> [value]: 'mdeaths'
#> [value]: 'fdeaths'
#> Error in rbindlist(ll.dts, use.names = TRUE): Answer requires 4 columns whereas one or more item(s) in the input list has only 3 columns. This could be because the items in the list may not all have identical column names or some of the items may have duplicate names. In either case, if you're aware of this and would like to fill those missing columns, set the argument 'fill=TRUE'.
```

<sup>Created on 2019-07-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any  idea why this behaviour would have changed?

**Comment by christophsax** [comment] 2019-08-02 20:09
Thanks for spotting this!

This used to work because `ts_c` did not care about the names but only about the positions. 

In the latest version, time and value columns are automatically determined for each ts object and concatenated correctly, independent of the position. So it should be now the case that, consistently, for all ts-functions, the first object determines the colnames and the colorder of the output.

Here is an example:

``` r
require(tsbox)
#> Loading required package: tsbox

ts1 <- ts_df(mdeaths)
ts2 <- ts_df(fdeaths)
colnames(ts1) <- c("time1", "value1")
colnames(ts2) <- c("time2", "value2")
ts2 <- ts_span(ts2[, c(2, 1)], end = 1977)
#> [time]: 'time2' [value]: 'value2'


head(ts_c(ts2, ts1))
#> [time]: 'time2' [value]: 'value2'
#> [time]: 'time1' [value]: 'value1'
#>    id value2      time2
#> 1 ts2    901 1974-01-01
#> 2 ts2    689 1974-02-01
#> 3 ts2    827 1974-03-01
#> 4 ts2    677 1974-04-01
#> 5 ts2    522 1974-05-01
#> 6 ts2    406 1974-06-01
head(ts_bind(ts2, ts1))
#> [time]: 'time2' [value]: 'value2' 
#> [time]: 'time1' [value]: 'value1'
#>   value2      time2
#> 1    901 1974-01-01
#> 2    689 1974-02-01
#> 3    827 1974-03-01
#> 4    677 1974-04-01
#> 5    522 1974-05-01
#> 6    406 1974-06-01
head(ts_chain(ts2, ts1))
#> [time]: 'time1' [value]: 'value1'
#> [time]: 'time2' [value]: 'value2'
#>   value2      time2
#> 1    901 1974-01-01
#> 2    689 1974-02-01
#> 3    827 1974-03-01
#> 4    677 1974-04-01
#> 5    522 1974-05-01
#> 6    406 1974-06-01
head(ts_pc(ts2))
#> [time]: 'time2' [value]: 'value2' 
#> [time]: 'time2' [value]: 'value2'
#>      value2      time2
#> 1        NA 1974-01-01
#> 2 -23.52941 1974-02-01
#> 3  20.02903 1974-03-01
#> 4 -18.13785 1974-04-01
#> 5 -22.89513 1974-05-01
#> 6 -22.22222 1974-06-01
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by christophsax** [comment] 2019-08-06 06:51
On CRAN now, feel free to re-open if there are still issues

**Closed by christophsax** 2019-08-06 06:51 UTC
